trigger:
  branches:
    include:
    - master
    - releases/*
  paths:
    include:
    - react-frontend
    exclude:
    - README.md

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    yarn install --production=false
    yarn run build
    cp ./package.json ./build/package.json
    cp ./production.server.js ./build/production.server.js
    cp ./Dockerfile ./build/Dockerfile
  workingDirectory: './react-frontend'
  displayName: 'yarn install, yarn build'

- script: |
    yarn install --production=true
  workingDirectory: './react-frontend/build'
  displayName: 'yarn install express'

- task: ArchiveFiles@1
  displayName: 'Archive files '
  inputs:
    rootFolder: './react-frontend/build'
    includeRootFolder: false

- task: CopyFiles@2
  displayName: 'Copy File to: $(TargetFolder)'
  inputs:
    SourceFolder: '$(Build.ArtifactStagingDirectory)'
    Contents: '$(Build.BuildId).zip'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\ArtifactsToBePublished'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\ArtifactsToBePublished'