trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    yarn install
    yarn run build
    copy ./package.json ./build/package.json
    copy ./production.server.js ./build/production.server.js
  workingDirectory: './react-frontend'
  displayName: 'yarn install, yarn build'

- script: |
    yarn install --production=true
  workingDirectory: './react-frontend/build'
  displayName: 'yarn install express'

- task: ArchiveFiles@1
  displayName: 'Archive files '
  inputs:
    rootFolder: './react-frontend/build'
    includeRootFolder: false

- task: CopyFiles@2
  displayName: 'Copy File to: $(TargetFolder)'
  inputs:
    SourceFolder: '$(Build.ArtifactStagingDirectory)'
    Contents: '$(Build.BuildId).zip'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\ArtifactsToBePublished'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\ArtifactsToBePublished'