trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: Npm@0
  displayName: 'npm install'
  inputs:
    cwd: './react-frontend'
    arguments: '--force'

- task: Npm@1
  displayName: 'npm build'
  inputs:
    command: custom
    workingDir: './react-frontend'
    verbose: false
    customCommand: run build

- task: ArchiveFiles@1
  displayName: 'Archive files '
  inputs:
    rootFolder: './react-frontend/build'
    includeRootFolder: false

- task: CopyFiles@2
  displayName: 'Copy File to: $(TargetFolder)'
  inputs:
    SourceFolder: '$(Build.ArtifactStagingDirectory)'
    Contents: '$(Build.BuildId).zip'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\ArtifactsToBePublished'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\ArtifactsToBePublished'