version: "3"
services:
    api:
        build: ./backend
        ports:
            - "5000:80"
        environment:
            - DefaultConnectionString=Server=db;Database=AlpakiDatabas;User=sa;Password=D.`(>q8'5d,ngL>H;
            - Seq:ApiKey=123456789
            - Seq:ServerUrl=http://seq:5341
        depends_on:
            - db
            - seq
    db:
        container_name: db
        image: "microsoft/mssql-server-linux"
        restart: always
        ports:
            - "1433:1433"
        expose: 
            - 1433
        volumes:
            - alpakisql:/var/opt/mssql
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "D.`(>q8'5d,ngL>H"
    seq:
        image: datalust/seq:latest
        ports:
            - "5341:80"
        environment:
            ACCEPT_EULA: Y
        restart: unless-stopped
        volumes:
            - alpakiseq:/data
volumes:
    alpakisql:
    alpakiseq: