POST http://localhost:8080/api/search?index=party-shop-index

{
    "count":false,
    "skip":0,
    "top":50,
    "searchMode":"any",
    "queryType":"simple",
    "facets":["is_available,count:5,sort:count"],
    "search":"kartka"
}