// <auto-generated />
using System;
using Alpaki.Moto.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Alpaki.Moto.Database.Migrations
{
    [DbContext(typeof(MotoDatabaseContext))]
    [Migration("20201015125137_AddMotoEventsMigration")]
    partial class AddMotoEventsMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Alpaki.Moto.Database.Models.Brand", b =>
                {
                    b.Property<long>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("BrandId");

                    b.ToTable("Brand","Moto");
                });

            modelBuilder.Entity("Alpaki.Moto.Database.Models.BrandDomainEvent", b =>
                {
                    b.Property<Guid>("BrandDomainEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("BrandId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DomainEventType")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("Processed")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("BrandDomainEventId");

                    b.HasIndex("BrandId");

                    b.ToTable("BrandDomainEvent","Moto");
                });

            modelBuilder.Entity("Alpaki.Moto.Database.Models.Model", b =>
                {
                    b.Property<long>("ModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("BrandId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.HasKey("ModelId");

                    b.HasIndex("BrandId");

                    b.ToTable("Model","Moto");
                });

            modelBuilder.Entity("Alpaki.Moto.Database.Models.BrandDomainEvent", b =>
                {
                    b.HasOne("Alpaki.Moto.Database.Models.Brand", "Brand")
                        .WithMany("BrandDomainEvents")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Alpaki.Moto.Database.Models.Model", b =>
                {
                    b.HasOne("Alpaki.Moto.Database.Models.Brand", "Brand")
                        .WithMany("Models")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
