// <auto-generated />
using Alpaki.Moto.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Alpaki.Moto.Database.Migrations
{
    [DbContext(typeof(MotoDatabaseContext))]
    [Migration("20200921062651_SeedBrandsMigration")]
    partial class SeedBrandsMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Alpaki.Moto.Database.Models.Brand", b =>
                {
                    b.Property<long>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.HasKey("BrandId");

                    b.ToTable("Brand","Moto");

                    b.HasData(
                        new
                        {
                            BrandId = 1L,
                            BrandName = "AC"
                        },
                        new
                        {
                            BrandId = 2L,
                            BrandName = "AC PROPULSION"
                        },
                        new
                        {
                            BrandId = 3L,
                            BrandName = "ACURA"
                        },
                        new
                        {
                            BrandId = 4L,
                            BrandName = "A.D. TRAMONTANA"
                        },
                        new
                        {
                            BrandId = 5L,
                            BrandName = "ALFA ROMEO"
                        },
                        new
                        {
                            BrandId = 6L,
                            BrandName = "ALMAC"
                        },
                        new
                        {
                            BrandId = 7L,
                            BrandName = "ALTERNATIVE CARS"
                        },
                        new
                        {
                            BrandId = 8L,
                            BrandName = "AMUZA"
                        },
                        new
                        {
                            BrandId = 9L,
                            BrandName = "ANTEROS"
                        },
                        new
                        {
                            BrandId = 10L,
                            BrandName = "ARASH"
                        },
                        new
                        {
                            BrandId = 11L,
                            BrandName = "ARIEL"
                        },
                        new
                        {
                            BrandId = 12L,
                            BrandName = "ARRINERA"
                        },
                        new
                        {
                            BrandId = 13L,
                            BrandName = "ASL"
                        },
                        new
                        {
                            BrandId = 14L,
                            BrandName = "ASTERIO"
                        },
                        new
                        {
                            BrandId = 15L,
                            BrandName = "ASTON MARTIN"
                        },
                        new
                        {
                            BrandId = 16L,
                            BrandName = "AUDI"
                        },
                        new
                        {
                            BrandId = 17L,
                            BrandName = "BAC"
                        },
                        new
                        {
                            BrandId = 18L,
                            BrandName = "BAJAJ"
                        },
                        new
                        {
                            BrandId = 19L,
                            BrandName = "BEIJING AUTOMOBILE WORKS"
                        },
                        new
                        {
                            BrandId = 20L,
                            BrandName = "BENTLEY"
                        },
                        new
                        {
                            BrandId = 21L,
                            BrandName = "BMW"
                        },
                        new
                        {
                            BrandId = 22L,
                            BrandName = "BOLLORÉ"
                        },
                        new
                        {
                            BrandId = 23L,
                            BrandName = "BOLWELL"
                        },
                        new
                        {
                            BrandId = 24L,
                            BrandName = "BRILLIANCE / HUACHEN"
                        },
                        new
                        {
                            BrandId = 25L,
                            BrandName = "BRISTOL"
                        },
                        new
                        {
                            BrandId = 26L,
                            BrandName = "BRITISH LEYLAND"
                        },
                        new
                        {
                            BrandId = 27L,
                            BrandName = "BRM BUGGY"
                        },
                        new
                        {
                            BrandId = 28L,
                            BrandName = "BROOKE"
                        },
                        new
                        {
                            BrandId = 29L,
                            BrandName = "BUDDY"
                        },
                        new
                        {
                            BrandId = 30L,
                            BrandName = "BUFORI"
                        },
                        new
                        {
                            BrandId = 31L,
                            BrandName = "BUGATTI"
                        },
                        new
                        {
                            BrandId = 32L,
                            BrandName = "BUICK"
                        },
                        new
                        {
                            BrandId = 33L,
                            BrandName = "BYD"
                        },
                        new
                        {
                            BrandId = 34L,
                            BrandName = "CADILLAC"
                        },
                        new
                        {
                            BrandId = 35L,
                            BrandName = "CAPARO"
                        },
                        new
                        {
                            BrandId = 36L,
                            BrandName = "CARBONTECH"
                        },
                        new
                        {
                            BrandId = 37L,
                            BrandName = "CARICE"
                        },
                        new
                        {
                            BrandId = 38L,
                            BrandName = "CHANG'AN"
                        },
                        new
                        {
                            BrandId = 39L,
                            BrandName = "CHANGHE"
                        },
                        new
                        {
                            BrandId = 40L,
                            BrandName = "CHERY"
                        },
                        new
                        {
                            BrandId = 41L,
                            BrandName = "CHEVROLET"
                        },
                        new
                        {
                            BrandId = 42L,
                            BrandName = "CHEVRON"
                        },
                        new
                        {
                            BrandId = 43L,
                            BrandName = "CITROËN"
                        },
                        new
                        {
                            BrandId = 44L,
                            BrandName = "CHRYSLER"
                        },
                        new
                        {
                            BrandId = 45L,
                            BrandName = "COMMUTER CARS"
                        },
                        new
                        {
                            BrandId = 46L,
                            BrandName = "CONNAUGHT"
                        },
                        new
                        {
                            BrandId = 47L,
                            BrandName = "COVINI"
                        },
                        new
                        {
                            BrandId = 48L,
                            BrandName = "DACIA"
                        },
                        new
                        {
                            BrandId = 49L,
                            BrandName = "DAIHATSU"
                        },
                        new
                        {
                            BrandId = 50L,
                            BrandName = "DATSUN"
                        },
                        new
                        {
                            BrandId = 51L,
                            BrandName = "DE LA CHAPELLE"
                        },
                        new
                        {
                            BrandId = 52L,
                            BrandName = "DMC"
                        },
                        new
                        {
                            BrandId = 53L,
                            BrandName = "DIARDI"
                        },
                        new
                        {
                            BrandId = 54L,
                            BrandName = "DODGE"
                        },
                        new
                        {
                            BrandId = 55L,
                            BrandName = "DONKERVOORT"
                        },
                        new
                        {
                            BrandId = 56L,
                            BrandName = "DONGFENG"
                        },
                        new
                        {
                            BrandId = 57L,
                            BrandName = "DONTO"
                        },
                        new
                        {
                            BrandId = 58L,
                            BrandName = "DS AUTOMOBILES"
                        },
                        new
                        {
                            BrandId = 59L,
                            BrandName = "DYNASTI ELECTRIC CAR CORP."
                        },
                        new
                        {
                            BrandId = 60L,
                            BrandName = "E-VADE"
                        },
                        new
                        {
                            BrandId = 61L,
                            BrandName = "EFFEDI"
                        },
                        new
                        {
                            BrandId = 62L,
                            BrandName = "EGY-TECH ENGINEERING"
                        },
                        new
                        {
                            BrandId = 63L,
                            BrandName = "ELECTRIC RACEABOUT"
                        },
                        new
                        {
                            BrandId = 64L,
                            BrandName = "ELFIN"
                        },
                        new
                        {
                            BrandId = 65L,
                            BrandName = "EMGRAND"
                        },
                        new
                        {
                            BrandId = 66L,
                            BrandName = "ENGLON"
                        },
                        new
                        {
                            BrandId = 67L,
                            BrandName = "ETERNITI"
                        },
                        new
                        {
                            BrandId = 68L,
                            BrandName = "ETOX"
                        },
                        new
                        {
                            BrandId = 69L,
                            BrandName = "EQUUS"
                        },
                        new
                        {
                            BrandId = 70L,
                            BrandName = "EXAGON"
                        },
                        new
                        {
                            BrandId = 71L,
                            BrandName = "FARALLI & MAZZANTI"
                        },
                        new
                        {
                            BrandId = 72L,
                            BrandName = "FAW"
                        },
                        new
                        {
                            BrandId = 73L,
                            BrandName = "FERRARI"
                        },
                        new
                        {
                            BrandId = 74L,
                            BrandName = "FIAT"
                        },
                        new
                        {
                            BrandId = 75L,
                            BrandName = "FISKER"
                        },
                        new
                        {
                            BrandId = 76L,
                            BrandName = "FODAY"
                        },
                        new
                        {
                            BrandId = 77L,
                            BrandName = "FORCE"
                        },
                        new
                        {
                            BrandId = 78L,
                            BrandName = "FORD"
                        },
                        new
                        {
                            BrandId = 79L,
                            BrandName = "FORD AUSTRALIA"
                        },
                        new
                        {
                            BrandId = 80L,
                            BrandName = "FORD GERMANY"
                        },
                        new
                        {
                            BrandId = 81L,
                            BrandName = "FORNASARI"
                        },
                        new
                        {
                            BrandId = 82L,
                            BrandName = "FRASER"
                        },
                        new
                        {
                            BrandId = 83L,
                            BrandName = "GAC GROUP"
                        },
                        new
                        {
                            BrandId = 84L,
                            BrandName = "GALPIN"
                        },
                        new
                        {
                            BrandId = 85L,
                            BrandName = "GEELY"
                        },
                        new
                        {
                            BrandId = 86L,
                            BrandName = "GENESIS"
                        },
                        new
                        {
                            BrandId = 87L,
                            BrandName = "GIBBS"
                        },
                        new
                        {
                            BrandId = 88L,
                            BrandName = "GILLET"
                        },
                        new
                        {
                            BrandId = 89L,
                            BrandName = "GINETTA"
                        },
                        new
                        {
                            BrandId = 90L,
                            BrandName = "GMC"
                        },
                        new
                        {
                            BrandId = 91L,
                            BrandName = "GONOW"
                        },
                        new
                        {
                            BrandId = 92L,
                            BrandName = "GREAT WALL / CHANGCHENG"
                        },
                        new
                        {
                            BrandId = 93L,
                            BrandName = "GREENTECH AUTOMOTIVE"
                        },
                        new
                        {
                            BrandId = 94L,
                            BrandName = "GRINNALL"
                        },
                        new
                        {
                            BrandId = 95L,
                            BrandName = "GTA MOTOR"
                        },
                        new
                        {
                            BrandId = 96L,
                            BrandName = "GUMPERT"
                        },
                        new
                        {
                            BrandId = 97L,
                            BrandName = "GURGEL"
                        },
                        new
                        {
                            BrandId = 98L,
                            BrandName = "HENNESSEY"
                        },
                        new
                        {
                            BrandId = 99L,
                            BrandName = "HINDUSTAN"
                        },
                        new
                        {
                            BrandId = 100L,
                            BrandName = "HOLDEN"
                        },
                        new
                        {
                            BrandId = 101L,
                            BrandName = "HONDA"
                        },
                        new
                        {
                            BrandId = 102L,
                            BrandName = "HONGQI"
                        },
                        new
                        {
                            BrandId = 103L,
                            BrandName = "HRADYESH"
                        },
                        new
                        {
                            BrandId = 104L,
                            BrandName = "HTT TECHNOLOGIES"
                        },
                        new
                        {
                            BrandId = 105L,
                            BrandName = "HULME"
                        },
                        new
                        {
                            BrandId = 106L,
                            BrandName = "HYUNDAI"
                        },
                        new
                        {
                            BrandId = 107L,
                            BrandName = "ICML"
                        },
                        new
                        {
                            BrandId = 108L,
                            BrandName = "IFR"
                        },
                        new
                        {
                            BrandId = 109L,
                            BrandName = "IRAN KHODRO"
                        },
                        new
                        {
                            BrandId = 110L,
                            BrandName = "IKCO"
                        },
                        new
                        {
                            BrandId = 111L,
                            BrandName = "IMPERIA"
                        },
                        new
                        {
                            BrandId = 112L,
                            BrandName = "INFINITI"
                        },
                        new
                        {
                            BrandId = 113L,
                            BrandName = "IVM"
                        },
                        new
                        {
                            BrandId = 114L,
                            BrandName = "INVICTA"
                        },
                        new
                        {
                            BrandId = 115L,
                            BrandName = "ISDERA"
                        },
                        new
                        {
                            BrandId = 116L,
                            BrandName = "ISUZU"
                        },
                        new
                        {
                            BrandId = 117L,
                            BrandName = "JAC"
                        },
                        new
                        {
                            BrandId = 118L,
                            BrandName = "JAGUAR"
                        },
                        new
                        {
                            BrandId = 119L,
                            BrandName = "JEEP"
                        },
                        new
                        {
                            BrandId = 120L,
                            BrandName = "JENSEN MOTORS"
                        },
                        new
                        {
                            BrandId = 121L,
                            BrandName = "JETCAR"
                        },
                        new
                        {
                            BrandId = 122L,
                            BrandName = "JONWAY"
                        },
                        new
                        {
                            BrandId = 123L,
                            BrandName = "JOSS"
                        },
                        new
                        {
                            BrandId = 124L,
                            BrandName = "KAIPAN"
                        },
                        new
                        {
                            BrandId = 125L,
                            BrandName = "KANTANKA"
                        },
                        new
                        {
                            BrandId = 126L,
                            BrandName = "KARMA"
                        },
                        new
                        {
                            BrandId = 127L,
                            BrandName = "KOENIGSEGG"
                        },
                        new
                        {
                            BrandId = 128L,
                            BrandName = "KORRES"
                        },
                        new
                        {
                            BrandId = 129L,
                            BrandName = "KIA"
                        },
                        new
                        {
                            BrandId = 130L,
                            BrandName = "KIAT"
                        },
                        new
                        {
                            BrandId = 131L,
                            BrandName = "KISH KHODRO"
                        },
                        new
                        {
                            BrandId = 132L,
                            BrandName = "KTM"
                        },
                        new
                        {
                            BrandId = 133L,
                            BrandName = "LADA"
                        },
                        new
                        {
                            BrandId = 134L,
                            BrandName = "LAMBORGHINI"
                        },
                        new
                        {
                            BrandId = 135L,
                            BrandName = "LANCIA"
                        },
                        new
                        {
                            BrandId = 136L,
                            BrandName = "LAND ROVER"
                        },
                        new
                        {
                            BrandId = 137L,
                            BrandName = "LANDWIND"
                        },
                        new
                        {
                            BrandId = 138L,
                            BrandName = "LARAKI"
                        },
                        new
                        {
                            BrandId = 139L,
                            BrandName = "LEBLANC"
                        },
                        new
                        {
                            BrandId = 140L,
                            BrandName = "LEITCH"
                        },
                        new
                        {
                            BrandId = 141L,
                            BrandName = "LEOPARD"
                        },
                        new
                        {
                            BrandId = 142L,
                            BrandName = "LEXUS"
                        },
                        new
                        {
                            BrandId = 143L,
                            BrandName = "LI-ION"
                        },
                        new
                        {
                            BrandId = 144L,
                            BrandName = "LIFAN"
                        },
                        new
                        {
                            BrandId = 145L,
                            BrandName = "LIGHTNING"
                        },
                        new
                        {
                            BrandId = 146L,
                            BrandName = "LINCOLN"
                        },
                        new
                        {
                            BrandId = 147L,
                            BrandName = "LISTER"
                        },
                        new
                        {
                            BrandId = 148L,
                            BrandName = "LOCAL MOTORS"
                        },
                        new
                        {
                            BrandId = 149L,
                            BrandName = "LOBINI"
                        },
                        new
                        {
                            BrandId = 150L,
                            BrandName = "LOTEC"
                        },
                        new
                        {
                            BrandId = 151L,
                            BrandName = "LOTUS CARS"
                        },
                        new
                        {
                            BrandId = 152L,
                            BrandName = "LUCRA CARS"
                        },
                        new
                        {
                            BrandId = 153L,
                            BrandName = "LUXGEN"
                        },
                        new
                        {
                            BrandId = 154L,
                            BrandName = "MAHINDRA"
                        },
                        new
                        {
                            BrandId = 155L,
                            BrandName = "MARUSSIA"
                        },
                        new
                        {
                            BrandId = 156L,
                            BrandName = "MARUTI SUZUKI"
                        },
                        new
                        {
                            BrandId = 157L,
                            BrandName = "MASERATI"
                        },
                        new
                        {
                            BrandId = 158L,
                            BrandName = "MASTRETTA"
                        },
                        new
                        {
                            BrandId = 159L,
                            BrandName = "MAZDA"
                        },
                        new
                        {
                            BrandId = 160L,
                            BrandName = "MCLAREN"
                        },
                        new
                        {
                            BrandId = 161L,
                            BrandName = "MERCEDES-BENZ"
                        },
                        new
                        {
                            BrandId = 162L,
                            BrandName = "MG"
                        },
                        new
                        {
                            BrandId = 163L,
                            BrandName = "MICRO"
                        },
                        new
                        {
                            BrandId = 164L,
                            BrandName = "MINI"
                        },
                        new
                        {
                            BrandId = 165L,
                            BrandName = "MITSUBISHI"
                        },
                        new
                        {
                            BrandId = 166L,
                            BrandName = "MITSUOKA"
                        },
                        new
                        {
                            BrandId = 167L,
                            BrandName = "MORGAN"
                        },
                        new
                        {
                            BrandId = 168L,
                            BrandName = "MULLEN"
                        },
                        new
                        {
                            BrandId = 169L,
                            BrandName = "MYCAR"
                        },
                        new
                        {
                            BrandId = 170L,
                            BrandName = "MYVI-PERODUA"
                        },
                        new
                        {
                            BrandId = 171L,
                            BrandName = "NISSAN"
                        },
                        new
                        {
                            BrandId = 172L,
                            BrandName = "NOBLE"
                        },
                        new
                        {
                            BrandId = 173L,
                            BrandName = "NOTA"
                        },
                        new
                        {
                            BrandId = 174L,
                            BrandName = "OLDSMOBILE"
                        },
                        new
                        {
                            BrandId = 175L,
                            BrandName = "OPEL"
                        },
                        new
                        {
                            BrandId = 176L,
                            BrandName = "OPTIMAL ENERGY"
                        },
                        new
                        {
                            BrandId = 177L,
                            BrandName = "ORCA"
                        },
                        new
                        {
                            BrandId = 178L,
                            BrandName = "OLTCIT"
                        },
                        new
                        {
                            BrandId = 179L,
                            BrandName = "PAGANI"
                        },
                        new
                        {
                            BrandId = 180L,
                            BrandName = "PANHARD"
                        },
                        new
                        {
                            BrandId = 181L,
                            BrandName = "PANOZ"
                        },
                        new
                        {
                            BrandId = 182L,
                            BrandName = "PERANA"
                        },
                        new
                        {
                            BrandId = 183L,
                            BrandName = "PERODUA"
                        },
                        new
                        {
                            BrandId = 184L,
                            BrandName = "PEUGEOT"
                        },
                        new
                        {
                            BrandId = 185L,
                            BrandName = "P.G.O."
                        },
                        new
                        {
                            BrandId = 186L,
                            BrandName = "POLARSUN"
                        },
                        new
                        {
                            BrandId = 187L,
                            BrandName = "PLYMOUTH"
                        },
                        new
                        {
                            BrandId = 188L,
                            BrandName = "PORSCHE"
                        },
                        new
                        {
                            BrandId = 189L,
                            BrandName = "PROTO"
                        },
                        new
                        {
                            BrandId = 190L,
                            BrandName = "OULLIM"
                        },
                        new
                        {
                            BrandId = 191L,
                            BrandName = "PROTON"
                        },
                        new
                        {
                            BrandId = 192L,
                            BrandName = "PURITALIA"
                        },
                        new
                        {
                            BrandId = 193L,
                            BrandName = "QOROS"
                        },
                        new
                        {
                            BrandId = 194L,
                            BrandName = "QVALE"
                        },
                        new
                        {
                            BrandId = 195L,
                            BrandName = "RADICAL"
                        },
                        new
                        {
                            BrandId = 196L,
                            BrandName = "RELIANT"
                        },
                        new
                        {
                            BrandId = 197L,
                            BrandName = "RENAULT"
                        },
                        new
                        {
                            BrandId = 198L,
                            BrandName = "REVA"
                        },
                        new
                        {
                            BrandId = 199L,
                            BrandName = "RIMAC"
                        },
                        new
                        {
                            BrandId = 200L,
                            BrandName = "RINSPEED"
                        },
                        new
                        {
                            BrandId = 201L,
                            BrandName = "RODING"
                        },
                        new
                        {
                            BrandId = 202L,
                            BrandName = "ROEWE"
                        },
                        new
                        {
                            BrandId = 203L,
                            BrandName = "ROLLS-ROYCE"
                        },
                        new
                        {
                            BrandId = 204L,
                            BrandName = "ROSSIN-BERTIN"
                        },
                        new
                        {
                            BrandId = 205L,
                            BrandName = "ROSSION"
                        },
                        new
                        {
                            BrandId = 206L,
                            BrandName = "ROVER"
                        },
                        new
                        {
                            BrandId = 207L,
                            BrandName = "SAAB"
                        },
                        new
                        {
                            BrandId = 208L,
                            BrandName = "SALEEN"
                        },
                        new
                        {
                            BrandId = 209L,
                            BrandName = "SAIC-GM-WULING"
                        },
                        new
                        {
                            BrandId = 210L,
                            BrandName = "SAIPA"
                        },
                        new
                        {
                            BrandId = 211L,
                            BrandName = "SAKER"
                        },
                        new
                        {
                            BrandId = 212L,
                            BrandName = "SAMSUNG"
                        },
                        new
                        {
                            BrandId = 213L,
                            BrandName = "SAN"
                        },
                        new
                        {
                            BrandId = 214L,
                            BrandName = "SBARRO"
                        },
                        new
                        {
                            BrandId = 215L,
                            BrandName = "SCION"
                        },
                        new
                        {
                            BrandId = 216L,
                            BrandName = "SEAT"
                        },
                        new
                        {
                            BrandId = 217L,
                            BrandName = "SHANGHAI MAPLE"
                        },
                        new
                        {
                            BrandId = 218L,
                            BrandName = "SIN"
                        },
                        new
                        {
                            BrandId = 219L,
                            BrandName = "ŠKODA"
                        },
                        new
                        {
                            BrandId = 220L,
                            BrandName = "SMART"
                        },
                        new
                        {
                            BrandId = 221L,
                            BrandName = "SPADA VETTURE SPORT"
                        },
                        new
                        {
                            BrandId = 222L,
                            BrandName = "SPYKER"
                        },
                        new
                        {
                            BrandId = 223L,
                            BrandName = "SSANGYONG"
                        },
                        new
                        {
                            BrandId = 224L,
                            BrandName = "SSC NORTH AMERICA"
                        },
                        new
                        {
                            BrandId = 225L,
                            BrandName = "STREET & RACING TECHNOLOGY"
                        },
                        new
                        {
                            BrandId = 226L,
                            BrandName = "SUBARU"
                        },
                        new
                        {
                            BrandId = 227L,
                            BrandName = "SUZUKI"
                        },
                        new
                        {
                            BrandId = 228L,
                            BrandName = "TANOM"
                        },
                        new
                        {
                            BrandId = 229L,
                            BrandName = "TATA"
                        },
                        new
                        {
                            BrandId = 230L,
                            BrandName = "TAURO"
                        },
                        new
                        {
                            BrandId = 231L,
                            BrandName = "TAWON CAR"
                        },
                        new
                        {
                            BrandId = 232L,
                            BrandName = "TD CARS"
                        },
                        new
                        {
                            BrandId = 233L,
                            BrandName = "TESLA"
                        },
                        new
                        {
                            BrandId = 234L,
                            BrandName = "THAI RUNG"
                        },
                        new
                        {
                            BrandId = 235L,
                            BrandName = "TOYOTA"
                        },
                        new
                        {
                            BrandId = 236L,
                            BrandName = "TREKKA"
                        },
                        new
                        {
                            BrandId = 237L,
                            BrandName = "TRIDENT"
                        },
                        new
                        {
                            BrandId = 238L,
                            BrandName = "TRIUMPH"
                        },
                        new
                        {
                            BrandId = 239L,
                            BrandName = "TROLLER"
                        },
                        new
                        {
                            BrandId = 240L,
                            BrandName = "TRUMPCHI"
                        },
                        new
                        {
                            BrandId = 241L,
                            BrandName = "TUSHEK"
                        },
                        new
                        {
                            BrandId = 242L,
                            BrandName = "TVR"
                        },
                        new
                        {
                            BrandId = 243L,
                            BrandName = "TVS"
                        },
                        new
                        {
                            BrandId = 244L,
                            BrandName = "ULTIMA"
                        },
                        new
                        {
                            BrandId = 245L,
                            BrandName = "UMM"
                        },
                        new
                        {
                            BrandId = 246L,
                            BrandName = "UEV"
                        },
                        new
                        {
                            BrandId = 247L,
                            BrandName = "URI"
                        },
                        new
                        {
                            BrandId = 248L,
                            BrandName = "UAZ"
                        },
                        new
                        {
                            BrandId = 249L,
                            BrandName = "VAUXHALL MOTORS"
                        },
                        new
                        {
                            BrandId = 250L,
                            BrandName = "VECTOR"
                        },
                        new
                        {
                            BrandId = 251L,
                            BrandName = "VENCER"
                        },
                        new
                        {
                            BrandId = 252L,
                            BrandName = "VENIRAUTO"
                        },
                        new
                        {
                            BrandId = 253L,
                            BrandName = "VENTURI"
                        },
                        new
                        {
                            BrandId = 254L,
                            BrandName = "VEPR"
                        },
                        new
                        {
                            BrandId = 255L,
                            BrandName = "VOLKSWAGEN"
                        },
                        new
                        {
                            BrandId = 256L,
                            BrandName = "VOLVO"
                        },
                        new
                        {
                            BrandId = 257L,
                            BrandName = "VINFAST"
                        },
                        new
                        {
                            BrandId = 258L,
                            BrandName = "W MOTORS"
                        },
                        new
                        {
                            BrandId = 259L,
                            BrandName = "WALLYSCAR"
                        },
                        new
                        {
                            BrandId = 260L,
                            BrandName = "WESTFIELD"
                        },
                        new
                        {
                            BrandId = 261L,
                            BrandName = "WHEEGO"
                        },
                        new
                        {
                            BrandId = 262L,
                            BrandName = "WIESMANN"
                        },
                        new
                        {
                            BrandId = 263L,
                            BrandName = "XENIA"
                        },
                        new
                        {
                            BrandId = 264L,
                            BrandName = "YES!"
                        },
                        new
                        {
                            BrandId = 265L,
                            BrandName = "YOUABIAN PUMA"
                        },
                        new
                        {
                            BrandId = 266L,
                            BrandName = "ZASTAVA AUTOMOBILES"
                        },
                        new
                        {
                            BrandId = 267L,
                            BrandName = "ZENDER CARS"
                        },
                        new
                        {
                            BrandId = 268L,
                            BrandName = "ZENOS CARS"
                        },
                        new
                        {
                            BrandId = 269L,
                            BrandName = "ZENVO"
                        },
                        new
                        {
                            BrandId = 270L,
                            BrandName = "ZIL"
                        },
                        new
                        {
                            BrandId = 271L,
                            BrandName = "ZX AUTO"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
