name: .NET Core + Angular

on:
  push:
    branches: [ master, frontend ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Build
      run: dotnet build backend/Alpaki.sln
    - name: Setup test database
      run: docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=test123!' -p 1433:1433 -d mcr.microsoft.com/mssql/server:2017-latest
    - name: Setup smtp server
      run: docker run -d -p 1025:1025 -p 8025:8025 mailhog/mailhog
    - name: Test
      run: dotnet test backend/Alpaki.sln
  front:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: AlpakiWeb
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.8
      uses: actions/setup-node@v1
      with:
        node-version: 12.8
    - name: Install dependencies
      run: yarn install
    - name: Lint
      run: yarn lint
    - name: Build
      run: yarn build
